#!/usr/bin/env python3
"""
extract_minesweeper_sprites.py
------------------------------
Converts classic Minesweeper PNG tiles and face icons into a single
TypeScript/React file (MinesweeperSprites.tsx) that exports each sprite as
an inline SVG component.

Inline SVG components are rendered directly in the DOM, so they inherit
CSS custom properties from the parent — unlike <img src="…svg"> which
is isolated. This is what allows every tile/face to adapt to any react95
theme colour.

Color mapping  (Win95 pixel → CSS variable):
  (189,189,189) / (192,192,192)   → transparent  (drawn by CSS background)
  (255,255,255)                   → var(--ms-hl)   bright highlight bevel
  (123,123,123) / (128,128,128)   → var(--ms-sh)   shadow bevel
  (0,0,0)                         → var(--ms-fg)   pure black / foreground
  (255,0,0)                       → var(--ms-red)
  (255,255,0)                     → var(--ms-yellow)
  (123,123,0)  / (128,128,0)      → var(--ms-yellow-dark)
  (0,0,255)                       → var(--ms-c1)  digit-1 blue
  (0,123,0)    / (0,128,0)        → var(--ms-c2)  digit-2 green
  (255,0,0)  [used for count-3]   → var(--ms-red)   (same as flag red)

Usage:
  python3 scripts/extract_minesweeper_sprites.py
"""

import os
import textwrap
from PIL import Image

ROOT       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS_DIR  = os.path.join(ROOT, "public", "icons")
OUT_FILE   = os.path.join(ROOT, "src", "apps", "Minesweeper", "MinesweeperSprites.tsx")

TRANSPARENT = object()  # sentinel: skip this pixel entirely

# ── Color mapping ─────────────────────────────────────────────────────────────
COLOR_MAP = {
    (189, 189, 189): TRANSPARENT,       # material bg → skip
    (192, 192, 192): TRANSPARENT,       # alt material bg
    (255, 255, 255): "var(--ms-hl)",    # bright highlight
    (123, 123, 123): "var(--ms-sh)",    # shadow
    (128, 128, 128): "var(--ms-sh)",    # alt shadow
    (0,   0,   0  ): "var(--ms-fg)",   # black / foreground
    (255, 0,   0  ): "var(--ms-red)",  # red
    (255, 255, 0  ): "var(--ms-yellow)",
    (123, 123, 0  ): "var(--ms-ydark)",
    (128, 128, 0  ): "var(--ms-ydark)",
    (0,   0,   255): "var(--ms-c1)",   # digit-1 blue
    (0,   123, 0  ): "var(--ms-c2)",   # digit-2 green
    (0,   128, 0  ): "var(--ms-c2)",
}

# Sprites to process: (source_png_name, strip_border_px, component_name)
SPRITES = [
    # ── tiles (strip 2-px bevel so CSS redraws it) ──
    ("minesweeper-tile-flag",     2, "TileFlag"),
    ("minesweeper-tile-mine",     2, "TileMine"),
    ("minesweeper-tile-mine-red", 2, "TileMineRed"),
    ("minesweeper-tile-mine-x",   2, "TileMineX"),
    ("minesweeper-tile-count-1",  2, "TileCount1"),
    ("minesweeper-tile-count-2",  2, "TileCount2"),
    ("minesweeper-tile-count-3",  2, "TileCount3"),
    ("minesweeper-tile-count-4",  2, "TileCount4"),
    ("minesweeper-tile-count-5",  2, "TileCount5"),
    ("minesweeper-tile-count-6",  2, "TileCount6"),
    ("minesweeper-tile-count-7",  2, "TileCount7"),
    ("minesweeper-tile-count-8",  2, "TileCount8"),
    # ── faces (strip 3-px bevel: 1 outer dark + 2 highlight + 3 shadow) ──
    ("minesweeper-face-smile",            3, "FaceSmile"),
    ("minesweeper-face-dead",             3, "FaceDead"),
    ("minesweeper-face-sunglasses",       3, "FaceSunglasses"),
    ("minesweeper-face-scared",           3, "FaceScared"),
    ("minesweeper-face-depressed-smile",  3, "FaceDepressedSmile"),
]


def rgb(pixel):
    return pixel[:3]


def build_rects(pixels, width, height, skip):
    """Return a list of JSX rect strings for the inner (skip-stripped) region."""
    rects = []
    for y in range(skip, height - skip):
        for x in range(skip, width - skip):
            p = rgb(pixels[y * width + x])
            fill = COLOR_MAP.get(p)
            if fill is TRANSPARENT:
                continue  # intentionally transparent → no rect
            if fill is None:
                # Unknown colour — emit as literal hex so nothing is silently lost
                fill = "#{:02x}{:02x}{:02x}".format(*p)
            sx = x - skip
            sy = y - skip
            rects.append(f'      <rect x={{{sx}}} y={{{sy}}} width={{1}} height={{1}} fill="{fill}"/>')
    return rects


def process_sprite(png_name, skip):
    src = os.path.join(ICONS_DIR, f"{png_name}.png")
    img = Image.open(src).convert("RGBA")
    w, h = img.size
    pixels = list(img.getdata())
    rects = build_rects(pixels, w, h, skip)
    iw = w - 2 * skip
    ih = h - 2 * skip
    return iw, ih, rects


def main():
    header = textwrap.dedent("""\
        // AUTO-GENERATED by scripts/extract_minesweeper_sprites.py — do not edit by hand.
        // Each component renders an inline SVG pixel-art sprite that inherits CSS custom
        // properties from the parent, enabling full react95 theme support.
        //
        // Required CSS variables on a parent element (set via styled-components Layout):
        //   --ms-hl      bright highlight bevel  (theme.borderLightest)
        //   --ms-sh      shadow bevel             (theme.borderDark)
        //   --ms-fg      foreground / black       (#000)
        //   --ms-red     red accents              (#f00)
        //   --ms-yellow  smiley face yellow       (#ff0)
        //   --ms-ydark   smiley dark yellow       (#7b7b00)
        //   --ms-c1      digit-1 colour           (#00f)
        //   --ms-c2      digit-2 colour           (#007b00)

        import type { SVGProps } from "react";

        type P = SVGProps<SVGSVGElement>;

    """)

    parts = [header]

    for png_name, skip, comp_name in SPRITES:
        try:
            iw, ih, rects = process_sprite(png_name, skip)
        except FileNotFoundError:
            print(f"  SKIP (not found): {png_name}.png")
            continue

        rect_block = "\n".join(rects) if rects else "      {/* empty */}"
        component = (
            f"export function {comp_name}(props: P) {{\n"
            f"  return (\n"
            f"    <svg\n"
            f"      xmlns=\"http://www.w3.org/2000/svg\"\n"
            f"      width={{{iw}}}\n"
            f"      height={{{ih}}}\n"
            f"      viewBox={{`0 0 {iw} {ih}`}}\n"
            f"      shapeRendering=\"crispEdges\"\n"
            f"      {{...props}}\n"
            f"    >\n"
            f"{rect_block}\n"
            f"    </svg>\n"
            f"  );\n"
            f"}}\n"
        )
        parts.append(component)
        print(f"  OK  {comp_name}  ({iw}×{ih})")

    with open(OUT_FILE, "w") as f:
        f.write("\n".join(parts))

    print(f"\nWritten: {OUT_FILE}")


if __name__ == "__main__":
    print("Generating MinesweeperSprites.tsx …")
    main()
