import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, '../public/cursors');
const destFile = path.join(__dirname, '../src/data/cursorsVfs.generated.ts');

const files = fs.readdirSync(srcDir);
const nodes = [];

for (const file of files) {
  if (file === '.DS_Store' || file === 'readme.txt' || file === 'windows-xp-1.crs') {
    continue;
  }
  const filePath = path.join(srcDir, file);
  const stat = fs.statSync(filePath);
  if (!stat.isFile()) continue;

  const data = fs.readFileSync(filePath);
  const base64 = data.toString('base64');
  const ext = path.extname(file).toLowerCase();
  
  let mime = 'application/octet-stream';
  if (ext === '.cur') mime = 'image/x-icon';
  else if (ext === '.ani') mime = 'application/octet-stream'; // standard for ani

  const dataUrl = `data:${mime};base64,${base64}`;

  nodes.push({
    name: file,
    type: 'file',
    content: dataUrl,
    system: true,
    created: Date.now()
  });
}

const fileContent = `// Auto-generated by scripts/generateCursorsVfs.js — do not edit by hand.
import { type VfsNode } from "../store/vfsStore";

export const CURSORS_VFS_NODES: VfsNode[] = ${JSON.stringify(nodes, null, 2)};
`;

fs.writeFileSync(destFile, fileContent);
console.log(`Generated ${nodes.length} cursor nodes inside ${destFile}`);
