import type { VfsNode } from "../store/vfsStore";

/**
 * The default wallpapers live — like in real Windows Me — as .bmp files in
 * C:\Windows\Web\Wallpaper, served from /windows/web/wallpaper/. The list
 * here must match the files generated by scripts/gen-wallpapers.mjs.
 */
export const WALLPAPER_DIR = "C:\\Windows\\Web\\Wallpaper";
export const WALLPAPER_URL_BASE = "/windows/web/wallpaper";

export const DEFAULT_WALLPAPER_FILES = [
  "Black Thatch.bmp",
  "Blue Rivets.bmp",
  "Bubbles.bmp",
  "Carved Stone.bmp",
  "Circles.bmp",
  "Diagonal Sand.bmp",
  "Gold Petals.bmp",
  "Houndstooth.bmp",
  "Iceberg.bmp",
  "Ocean Wave.bmp",
  "Pinstripe.bmp",
  "Santa Fe Stucco.bmp",
  "Straw Mat.bmp",
  "Tiles.bmp",
  "Waves.bmp",
];

const IMAGE_EXTS = [".bmp", ".png", ".jpg", ".jpeg", ".gif"];

export function isImageFile(name: string): boolean {
  const lower = name.toLowerCase();
  return IMAGE_EXTS.some((e) => lower.endsWith(e));
}

/**
 * Resolve a VFS path to a browser-displayable URL. Default wallpapers map to
 * their static file; user files (e.g. saved from Paint) hold a data URL in
 * their VFS content.
 */
export function wallpaperUrl(
  vfsPath: string,
  readVfs: (path: string) => string | null,
): string | null {
  const lower = vfsPath.toLowerCase();
  const dirLower = WALLPAPER_DIR.toLowerCase() + "\\";
  if (lower.startsWith(dirLower)) {
    const name = vfsPath.slice(dirLower.length);
    const known = DEFAULT_WALLPAPER_FILES.find(
      (f) => f.toLowerCase() === name.toLowerCase(),
    );
    if (known) return `${WALLPAPER_URL_BASE}/${encodeURIComponent(known)}`;
  }
  const content = readVfs(vfsPath);
  if (content && content.startsWith("data:image")) return content;
  return null;
}

/** Display name for the wallpaper list ("Gold Petals.bmp" → "Gold Petals"). */
export function wallpaperLabel(vfsPath: string): string {
  const name = vfsPath.split("\\").pop() ?? vfsPath;
  return name.replace(/\.(bmp|png|jpe?g|gif)$/i, "");
}

/** VFS nodes for C:\Windows\Web\Wallpaper (seeded in vfsStore). */
export function wallpaperVfsNodes(): VfsNode[] {
  return DEFAULT_WALLPAPER_FILES.map((name) => ({
    name,
    type: "file" as const,
    system: true,
    created: Date.now(),
  }));
}
