name: Deploy RSNRA Art

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux]
    steps:
      - name: Update & Restart Service
        run: |
          cd /home/resonaura/apps/rsnra-art
          git pull
          pnpm install
          pnpm build
          pm2 restart rsnra-art
